import{a as b,S as v,i as a}from"./assets/vendor-C2ySes1p.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&d(c)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function d(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const w="https://pixabay.com/api/",S="38421129-385ad5ee77a37193a2d5ae11d";async function u(o,r){return b.get(w,{params:{key:S,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r}}).then(e=>e.data)}const f=document.querySelector(".gallery"),m=document.querySelector(".load-more"),q=new v(".gallery a",{captionsData:"alt",captionDelay:250}),h=document.querySelector(".loader");function y(o){const r=o.map(e=>`
        <li class="gallery-item">
        <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}"/>
        </a>
        
        <div class="info">
  <p><b>Likes: </b>${e.likes}</p>
  <p><b>Views: </b>${e.views}</p>
  <p><b>Comments: </b>${e.comments}</p>
  <p><b>Downloads: </b>${e.downloads}</p>
</div>
        </li>`).join("");f.insertAdjacentHTML("beforeend",r),q.refresh()}function B(){f.innerHTML=""}function p(){h.classList.remove("hidden")}function g(){h.classList.add("hidden")}function M(){m.classList.remove("hidden")}function l(){m.classList.add("hidden")}let n=1,i="";const L=15,P=document.querySelector(".load-more");P.addEventListener("click",O);const $=document.querySelector(".form");$.addEventListener("submit",E);async function E(o){if(o.preventDefault(),i=o.target.elements["search-text"].value.trim(),!i){a.error({message:"Please enter a search query"});return}n=1,B(),l(),p();try{const r=await u(i,n),e=r.hits;if(e.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}y(e),n*L<r.totalHits?M():(l(),a.info({message:"We're sorry, but you've reached the end of search results."}))}catch(r){a.error({message:r.message})}finally{g()}}async function O(){n+=1,p();try{const o=await u(i,n),r=o.hits;y(r),n*L>=o.totalHits&&(l(),a.info({message:"We're sorry, but you've reached the end of search results."}));const{height:e}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}catch(o){a.error({message:o.message})}finally{g()}}
//# sourceMappingURL=index.js.map
