import{a as w,S as v,i as a}from"./assets/vendor-C2ySes1p.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&d(l)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function d(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const S="https://pixabay.com/api/",q="38421129-385ad5ee77a37193a2d5ae11d";async function u(o,r){return(await w.get(S,{params:{key:q,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r}})).data}const f=document.querySelector(".gallery"),m=document.querySelector(".load-more"),B=new v(".gallery a",{captionsData:"alt",captionDelay:250}),y=document.querySelector(".loader");function h(o){const r=o.map(e=>`
        <li class="gallery-item">
        <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}"/>
        </a>
        
        <div class="info">
  <p><b>Likes: </b>${e.likes}</p>
  <p><b>Views: </b>${e.views}</p>
  <p><b>Comments: </b>${e.comments}</p>
  <p><b>Downloads: </b>${e.downloads}</p>
</div>
        </li>`).join("");f.insertAdjacentHTML("beforeend",r),B.refresh()}function M(){f.innerHTML=""}function p(){y.classList.remove("hidden")}function g(){y.classList.add("hidden")}function L(){m.classList.remove("hidden")}function c(){m.classList.add("hidden")}let n=1,i="";const b=15,P=document.querySelector(".load-more");P.addEventListener("click",O);const $=document.querySelector(".form");$.addEventListener("submit",E);async function E(o){if(o.preventDefault(),i=o.target.elements["search-text"].value.trim(),!i){a.error({message:"Please enter a search query"});return}n=1,M(),c(),p();try{const r=await u(i,n),e=r.hits;if(e.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}h(e),n*b<r.totalHits?L():(c(),a.info({message:"We're sorry, but you've reached the end of search results."}))}catch(r){a.error({message:r.message})}finally{g()}}async function O(){n+=1,c(),p();try{const o=await u(i,n),r=o.hits;h(r),n*b>=o.totalHits?L():(c(),a.info({message:"We're sorry, but you've reached the end of search results."}));const{height:e}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}catch(o){a.error({message:o.message})}finally{g()}}
//# sourceMappingURL=index.js.map
